workspace:
  base: /drone
  path: src

branches: [master, stable10, stable9.1, stable9]

clone:
  git:
    image: plugins/git
    depth: 50

pipeline:
  restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false
      event: [push, pull_request]

  composer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - ./tests/drone/composer-install.sh
    when:
      event: [push, pull_request]

  yarn:
    image: owncloudci/nodejs:latest
    pull: true
    commands:
      - ./tests/drone/yarn-install.sh
    when:
      event: [push, pull_request]

  rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - lib/composer
      - core/vendor
      - build/node_modules
    when:
      local: false
      event: [ push ]

  flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [push]

  javascript:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    group: test
    commands:
      - ./tests/drone/test-javascript.sh

  phpunit:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    group: test
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DB_TYPE=mariadb
    commands:
      - ./tests/drone/test-phpunit.sh

services:
  database:
    image: ${DATABASE}
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud

matrix:

  PHP_VERSION:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
  DATABASE:
    - mysql:5.7
    - mariadb:5.5
    - mariadb:10.1
    - mariadb:10.2
    - mariadb:10.3
